name: Publish Docs
on:
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Publish Docs
      env:
        BUILD_BOT_PASSWORD: ${{ secrets.BUILD_BOT_PASSWORD }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: .\build.ps1 publish --no-tests --trigger publish-docs
